version: '3.10'
services:
    db:
       image: postgres
       volumes:
           - ./data/db:/var/lib/postgresql/data
       environment:
           POSTGRES_PASSWORD: 123456
    web:
       build: .
       command: python /code/manage.py runserver 0.0.0.0:8000
       ports:
           - 8000:8000
       depends_on:
           - db