# Generated by Django 4.0.3 on 2022-03-14 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_message_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(default=1, verbose_name='Текст сообщения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='tickets.ticket'),
            preserve_default=False,
        ),
    ]
